In [2]:
import numpy as np 
import pandas as pd 
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, Normalizer

In [3]:
train_df= pd.read_csv(r'C:\Users\Arvind Vasa\AI-ML\myprojects\mnist_end_to_end\artifacts\train_data.csv')
test_df= pd.read_csv(r'C:\Users\Arvind Vasa\AI-ML\myprojects\mnist_end_to_end\artifacts\test_data.csv')
train_df.shape

(60000, 785)

In [4]:
x_train, y_train= train_df.drop('label', axis=1), train_df['label']
x_test, y_test= test_df.drop('label', axis=1), train_df['label']

In [5]:
preprocessor= ColumnTransformer(
    transformers=[
        ("Normalize", StandardScaler(), x_train.columns)
    ]
)

In [6]:
x_train_scaled= pd.DataFrame(preprocessor.fit_transform(x_train), columns=x_train.columns)
x_test_scaled= pd.DataFrame(preprocessor.fit_transform(x_test), columns=x_train.columns)

In [7]:
%pwd

'c:\\Users\\Arvind Vasa\\AI-ML\\myprojects\\mnist_end_to_end\\research'

In [8]:
import pickle
import os

os.chdir('../')
preprocessor_path= os.path.join('artifacts','preprocessor.pkl')
with open(preprocessor_path, 'wb') as preprocess_file:
    pickle.dump(preprocessor ,preprocess_file)

In [11]:
x_train.values[:, :-1]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
x= np.array([[1,2,3,4], [1,2,3,4]])
x[:,:-1]


array([[1, 2, 3],
       [1, 2, 3]])

In [24]:
x_train.values.reshape(x_train.values.shape[0], 28, 28)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [23]:
x_train.values.shape[0]

60000

In [20]:
x_train.values[:,:-1].reshape(x_train.values.shape[0], 28, 28)

ValueError: cannot reshape array of size 46980000 into shape (60000,28,28)